// Generated by Landing Page Scaffolder — 2026-08-10
// Stack: Next.js 14+ App Router, React, Tailwind CSS
// Design style: clean-minimal | Copy framework: PAS (Problem → Agitate → Solution)
// Audience: 职场新人

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FluentUp | 职场英语陪练 — 邮件/会议/汇报/面试全覆盖",
  description:
    "AI模拟真实职场场景：英文邮件、跨国会议、工作汇报、外企面试。每天15分钟，30天建立职场英语自信。免费试用7天。",
  openGraph: {
    title: "FluentUp | 职场英语陪练 — 邮件/会议/汇报/面试全覆盖",
    description:
      "AI模拟真实职场场景：英文邮件、跨国会议、工作汇报、外企面试。每天15分钟，30天建立职场英语自信。",
    type: "website",
  },
};

const faqCareer = [
  {
    q: "我英语四级水平，跟得上吗？",
    a: "跟得上。FluentUp会先做水平测试，从你当前级别开始。职场场景从简单的邮件往来开始，逐步过渡到会议和汇报，AI会根据你的表现自动调整难度。",
  },
  {
    q: "和通用英语学习APP有什么不同？",
    a: "FluentUp不教日常对话和语法，只练职场用得上的：邮件、会议、汇报、面试、small talk。每个场景都是真实工作情境，练完第二天就能用。",
  },
  {
    q: "每天需要多长时间？",
    a: "建议每天15-20分钟，一个场景模块大约10-15分钟。通勤路上、午休时都能完成，不需要专门腾出大块时间。",
  },
  {
    q: "免费试用结束会自动扣费吗？",
    a: "不会。7天试用期内不绑定支付方式，到期后自动降为免费版，不会产生任何费用。确认继续用再付费，随时可取消。",
  },
];

const faqSchemaCareer = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqCareer.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

function Navbar() {
  return (
    <nav className="sticky top-0 z-50 border-b border-gray-200 bg-white/90 backdrop-blur-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
        <a href="#" className="text-xl font-bold text-gray-900">FluentUp</a>
        <div className="hidden items-center gap-8 md:flex">
          <a href="#features" className="font-medium text-gray-500 transition-colors hover:text-gray-900">功能</a>
          <a href="#testimonials" className="font-medium text-gray-500 transition-colors hover:text-gray-900">用户评价</a>
          <a href="#pricing" className="font-medium text-gray-500 transition-colors hover:text-gray-900">价格</a>
          <a href="#faq" className="font-medium text-gray-500 transition-colors hover:text-gray-900">常见问题</a>
          <a
            href="#cta"
            className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
          >
            免费试用
          </a>
        </div>
      </div>
    </nav>
  );
}

function Hero() {
  return (
    <section className="flex min-h-[80vh] flex-col items-center justify-center bg-white px-6 py-24 text-center">
      <div className="mx-auto max-w-4xl">
        {/* PAS: Problem in headline */}
        <h1 className="mb-6 text-5xl font-bold tracking-tight text-gray-900 md:text-6xl">
          英语不好，
          <br />
          <span className="text-blue-600">正在拖慢你的职业发展</span>
        </h1>
        {/* Agitate + Solution in subhead */}
        <p className="mx-auto mb-10 max-w-2xl text-xl text-gray-500">
          英文邮件反复修改、跨国会议不敢发言、晋升机会让给英语好的同事？FluentUp用AI模拟真实职场场景，每天15分钟，30天建立职场英语自信。
        </p>
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
          <a
            href="#cta"
            className="rounded-lg bg-blue-600 px-8 py-3 text-lg font-semibold text-white transition-colors hover:bg-blue-700"
          >
            免费试用7天
          </a>
          <a
            href="#features"
            className="rounded-lg border border-gray-300 px-8 py-3 text-lg font-semibold text-gray-700 transition-colors hover:bg-gray-50"
          >
            了解职场场景 →
          </a>
        </div>
        <p className="mt-4 text-sm text-gray-400">无需绑卡 · 7天Pro体验 · 随时取消</p>
      </div>
    </section>
  );
}

function Features() {
  const items = [
    { icon: "📧", title: "商务邮件写作", desc: "从请求、催促到拒绝、道歉，覆盖50+职场邮件场景。AI即时批改语气、措辞和语法，教你写得专业又得体。" },
    { icon: "🎙️", title: "会议英语实战", desc: "模拟跨国电话会、视频会、头脑风暴，练听懂不同口音、学会插话、表达观点和做会议总结。" },
    { icon: "📊", title: "工作汇报与演讲", desc: "周报汇报、项目提案、晋升答辩……AI当你的听众，帮你练逻辑表达、应对提问，告别背稿子。" },
    { icon: "🤝", title: "面试与社交", desc: "英文自我介绍、行为面试题、small talk、电梯演讲。模拟真实面试节奏，练到不紧张为止。" },
    { icon: "⏱️", title: "通勤路上就能练", desc: "每天15分钟，地铁上、午休时、睡前都能来一课。不用约课、不用赶时间，进度自动保存。" },
    { icon: "📈", title: "可量化的进步", desc: "发音、流利度、商务词汇量三维追踪，每月生成能力报告。看着自己的进步曲线，坚持更有动力。" },
  ];
  return (
    <section id="features" className="bg-gray-50 px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-4 text-center text-4xl font-bold text-gray-900">为职场新人量身打造</h2>
        <p className="mx-auto mb-16 max-w-2xl text-center text-lg text-gray-500">不是背单词，不是学语法，是练你真正用得上的职场英语</p>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {items.map((f) => (
            <div key={f.title} className="rounded-2xl border border-gray-200 bg-white p-8">
              <div className="mb-4 text-3xl">{f.icon}</div>
              <h3 className="mb-3 text-xl font-semibold text-gray-900">{f.title}</h3>
              <p className="text-gray-500">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Testimonials() {
  const items = [
    { quote: "入职三个月第一次独立接英文会议，居然全程跟上了还主动发了言。FluentUp的会议模拟真的有用，那些套话练多了自然就说出来了。", name: "David", title: "产品运营", company: "某互联网公司" },
    { quote: "以前写封英文邮件要查半小时模板，现在10分钟搞定，老板还夸我邮件写得professional。邮件批改功能值回票价。", name: "Emma", title: "市场专员", company: "某外企" },
    { quote: "英文面试前练了两周，行为面试题基本都覆盖到了。面试的时候不慌，表达比之前流利太多，拿到了心仪的offer。", name: "Michael", title: "刚跳槽成功", company: "某咨询公司" },
  ];
  return (
    <section id="testimonials" className="bg-white px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-16 text-center text-4xl font-bold text-gray-900">职场新人的真实反馈</h2>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {items.map((t) => (
            <div key={t.name} className="rounded-2xl border border-gray-200 bg-white p-8">
              <p className="mb-6 text-lg italic text-gray-600">&ldquo;{t.quote}&rdquo;</p>
              <div>
                <p className="font-semibold text-gray-900">{t.name}</p>
                <p className="text-sm text-gray-500">{t.title} · {t.company}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Pricing() {
  const plans = [
    { name: "免费版", price: "0", unit: "", desc: "先体验再决定", features: ["每天15分钟AI对话", "基础发音评分", "3个职场场景", "社区打卡"], cta: "免费开始", featured: false },
    { name: "Pro 职场版", price: "29", unit: "/月", desc: "最受欢迎，覆盖全部职场场景", features: ["无限AI对话时长", "全部职场场景库", "邮件写作批改", "会议/汇报/面试模拟", "详细能力报告", "个性化学习路径"], cta: "开始7天免费试用", featured: true },
    { name: "Pro 年付", price: "20", unit: "/月", desc: "年付¥239，省¥109", features: ["Pro全部功能", "1对1真人外教月课1节", "职场英语能力测评", "简历英文优化1次"], cta: "选年付更划算", featured: false },
  ];
  return (
    <section id="pricing" className="bg-gray-50 px-6 py-24">
      <div className="mx-auto max-w-5xl">
        <h2 className="mb-4 text-center text-4xl font-bold text-gray-900">投资自己，每天不到1块钱</h2>
        <p className="mx-auto mb-16 max-w-xl text-center text-lg text-gray-500">一顿外卖的钱，换一个不再被英语卡住的职业起点</p>
        <div className="grid gap-8 lg:grid-cols-3">
          {plans.map((p) => (
            <div
              key={p.name}
              className={`relative rounded-2xl bg-white p-8 text-center ${
                p.featured ? "border-2 border-blue-500 shadow-lg ring-4 ring-blue-500/10" : "border border-gray-200"
              }`}
            >
              {p.featured && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-blue-600 px-4 py-1 text-xs font-semibold text-white">
                  最受欢迎
                </div>
              )}
              <h3 className="mb-2 text-xl font-semibold text-gray-900">{p.name}</h3>
              <div className="my-6 text-5xl font-extrabold text-gray-900">
                ¥{p.price}
                <span className="text-base font-normal text-gray-500">{p.unit}</span>
              </div>
              <p className="mb-6 text-gray-500">{p.desc}</p>
              <ul className="mb-8 space-y-1 text-left text-gray-600">
                {p.features.map((feat) => (
                  <li key={feat} className="flex items-center gap-2 py-2">
                    <span className="font-bold text-blue-500">&#10003;</span> {feat}
                  </li>
                ))}
              </ul>
              <a
                href="#cta"
                className={`block w-full rounded-lg py-3 text-center font-semibold transition-colors ${
                  p.featured
                    ? "bg-blue-600 text-white hover:bg-blue-700"
                    : "border border-gray-300 text-gray-700 hover:bg-gray-50"
                }`}
              >
                {p.cta}
              </a>
            </div>
          ))}
        </div>
        <p className="mt-8 text-center text-sm text-gray-400">7天无理由退款 · 随时取消订阅 · 支持微信/支付宝</p>
      </div>
    </section>
  );
}

function FAQ() {
  return (
    <section id="faq" className="bg-white px-6 py-24">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchemaCareer) }}
      />
      <div className="mx-auto max-w-3xl">
        <h2 className="mb-12 text-center text-4xl font-bold text-gray-900">常见问题</h2>
        <div className="space-y-4">
          {faqCareer.map((item) => (
            <details key={item.q} className="group rounded-2xl border border-gray-200 bg-white p-6 open:shadow-md">
              <summary className="cursor-pointer text-lg font-semibold text-gray-900">
                {item.q}
                <span className="float-right text-gray-400 transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-4 text-gray-600">{item.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section id="cta" className="bg-blue-600 px-6 py-24 text-center text-white">
      <div className="mx-auto max-w-3xl">
        <h2 className="mb-4 text-4xl font-bold">别让英语成为你晋升路上的短板</h2>
        <p className="mb-10 text-xl opacity-90">7天免费Pro体验，不绑卡，随时取消。今天开始，30天后见分晓。</p>
        <a
          href="#"
          className="inline-block rounded-lg bg-white px-8 py-3 text-lg font-semibold text-blue-600 transition-colors hover:bg-gray-100"
        >
          免费开始练职场英语
        </a>
        <p className="mt-6 text-sm opacity-75">已有 20,000+ 职场新人在用 · 平均4周感受到进步</p>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-gray-200 bg-white px-6 py-10 text-center text-gray-500">
      <p>&copy; 2026 FluentUp. 帮每个职场新人跨过英语这道坎。</p>
    </footer>
  );
}

export default function CareerLandingPage() {
  return (
    <main>
      <Navbar />
      <Hero />
      <Features />
      <Testimonials />
      <Pricing />
      <FAQ />
      <CTASection />
      <Footer />
    </main>
  );
}
