// Generated by Landing Page Scaffolder — 2026-08-10
// Stack: Next.js 14+ App Router, React, Tailwind CSS
// Design style: bold-startup | Copy framework: BAB (Before → After → Bridge)
// Audience: 大学生

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FluentUp | 大学生英语口语陪练 — 四六级/雅思/日常对话",
  description:
    "AI外教24小时陪练口语，四六级、雅思、日常对话全覆盖。每天15分钟，从不敢开口到流利表达。学生专享价¥19/月起，立即免费体验。",
  openGraph: {
    title: "FluentUp | 大学生英语口语陪练 — 四六级/雅思/日常对话",
    description:
      "AI外教24小时陪练口语，四六级、雅思、日常对话全覆盖。每天15分钟，从不敢开口到流利表达。学生专享价¥19/月起。",
    type: "website",
  },
};

const faqStudent = [
  {
    q: "没有英语基础能用吗？",
    a: "可以。FluentUp会根据你的水平自动调整对话难度，从最简单的日常对话开始，说错了AI会用中文提示你，完全不怕尴尬。",
  },
  {
    q: "学生优惠怎么认证？",
    a: "注册后上传学生证照片或用教育邮箱（.edu.cn）验证，审核通过后立即解锁¥19/月学生价，在读期间一直有效。",
  },
  {
    q: "和真人外教课有什么区别？",
    a: "真人外教课贵、要约时间、说错了会紧张。FluentUp随时能练、不限次数、不怕犯错，适合日常高频练习；想练真人对话时，Pro年付每月还送1节真人外教课。",
  },
  {
    q: "免费版和Pro版差在哪？",
    a: "免费版每天15分钟、3个场景；Pro版不限时长、解锁全部考试专项和场景库、有详细发音报告和AI写作批改。7天Pro免费试用，不用绑卡。",
  },
];

const faqSchemaStudent = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqStudent.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

function Navbar() {
  return (
    <nav className="sticky top-0 z-50 border-b border-gray-200 bg-white/90 backdrop-blur-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
        <a href="#" className="text-xl font-black tracking-tight text-gray-900">
          FluentUp
        </a>
        <div className="hidden items-center gap-8 md:flex">
          <a href="#features" className="font-medium text-gray-500 transition-colors hover:text-gray-900">功能</a>
          <a href="#testimonials" className="font-medium text-gray-500 transition-colors hover:text-gray-900">同学评价</a>
          <a href="#pricing" className="font-medium text-gray-500 transition-colors hover:text-gray-900">价格</a>
          <a href="#faq" className="font-medium text-gray-500 transition-colors hover:text-gray-900">常见问题</a>
          <a
            href="#cta"
            className="rounded-lg bg-orange-500 px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-orange-600"
          >
            免费开始
          </a>
        </div>
      </div>
    </nav>
  );
}

function Hero() {
  return (
    <section className="flex min-h-[80vh] flex-col items-center justify-center bg-white px-6 py-24 text-center">
      <div className="mx-auto max-w-4xl">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-orange-200 bg-orange-50 px-4 py-1.5 text-sm font-medium text-orange-600">
          <span className="h-1.5 w-1.5 rounded-full bg-orange-500" />
          学生专享价 ¥19/月起
        </div>
        {/* BAB: Before → After in headline */}
        <h1 className="mb-6 text-5xl font-black tracking-tight text-gray-900 md:text-7xl">
          从不敢开口
          <br />
          <span className="bg-gradient-to-r from-orange-500 to-pink-500 bg-clip-text text-transparent">
            到流利对话
          </span>
        </h1>
        <p className="mx-auto mb-10 max-w-2xl text-xl text-gray-500">
          FluentUp AI外教陪你练四六级口语、雅思Part 2、校园日常对话。不用约课、不怕说错，每天15分钟，学生价¥19/月起。
        </p>
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
          <a
            href="#cta"
            className="rounded-lg bg-orange-500 px-8 py-3 text-lg font-semibold text-white transition-colors hover:bg-orange-600"
          >
            免费练7天
          </a>
          <a
            href="#features"
            className="rounded-lg border-2 border-orange-500 px-8 py-3 text-lg font-semibold text-orange-600 transition-colors hover:bg-orange-50"
          >
            看看怎么练 →
          </a>
        </div>
        <p className="mt-4 text-sm text-gray-400">无需绑卡 · 7天Pro体验 · 不好用直接卸载</p>
      </div>
    </section>
  );
}

function Features() {
  const items = [
    { icon: "🎯", title: "考试口语专项", desc: "四六级口语、雅思Part 1-3、托福独立口语，真题场景全覆盖。AI考官模拟真实考试流程，考完即时出分和改进建议。" },
    { icon: "🤖", title: "AI外教24小时在线", desc: "凌晨两点想练也没问题。不用约课、不用等老师、不怕被笑话。说错了AI会温柔纠正，还能反复练同一句话。" },
    { icon: "🎓", title: "学生专属价", desc: "Pro会员¥19/月，比一杯奶茶还便宜。支持教育优惠认证，年付再减，学生党无压力。" },
    { icon: "📱", title: "碎片时间就能练", desc: "食堂排队、通勤路上、睡前15分钟，打开手机就能练。进度自动同步，不用专门腾出大块时间。" },
    { icon: "🗣️", title: "真实场景对话", desc: "小组讨论、课堂展示、留学面试、交换生日常……从校园到留学场景，练的就是你真正用得上的英语。" },
    { icon: "📊", title: "看得见的进步", desc: "发音、流利度、词汇量三维评分，每周生成学习报告。对比一个月前的自己，进步一目了然。" },
  ];
  return (
    <section className="bg-orange-50/30 px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-4 text-center text-4xl font-black tracking-tight text-gray-900">为什么大学生都在用FluentUp</h2>
        <p className="mx-auto mb-16 max-w-2xl text-center text-lg text-gray-500">不是背单词APP，是真正让你敢开口、说得出的口语陪练</p>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {items.map((f) => (
            <div key={f.title} className="rounded-3xl bg-white p-8 shadow-xl">
              <div className="mb-4 text-3xl">{f.icon}</div>
              <h3 className="mb-3 text-xl font-semibold text-gray-900">{f.title}</h3>
              <p className="text-gray-500">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Testimonials() {
  const items = [
    { quote: "四级口语裸考C，用FluentUp练了两个月六级口语拿了A！AI考官比真人考官友善多了，不会紧张。", name: "小林", title: "大三学生", company: "某211高校" },
    { quote: "雅思口语从5.5到6.5，Part 2跟着AI练了大概40个话题卡，考试的时候完全不慌。学生价真的良心。", name: "Aaron", title: "大四", company: "准备申研中" },
    { quote: "以前跟外教说话脑子一片空白，现在每天和AI聊15分钟，见到真外教居然能自然接话了。", name: "思思", title: "大二", company: "英语社团成员" },
  ];
  return (
    <section className="bg-white px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-16 text-center text-4xl font-black tracking-tight text-gray-900">同学都在说</h2>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {items.map((t) => (
            <div key={t.name} className="rounded-2xl border border-gray-200 p-8">
              <p className="mb-6 text-lg italic text-gray-600">&ldquo;{t.quote}&rdquo;</p>
              <div>
                <p className="font-semibold text-gray-900">{t.name}</p>
                <p className="text-sm text-gray-500">{t.title} · {t.company}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Pricing() {
  const plans = [
    { name: "免费版", price: "0", unit: "", desc: "先试试看", features: ["每天15分钟AI对话", "基础发音评分", "3个场景话题", "社区学习打卡"], cta: "免费开始", featured: false },
    { name: "Pro 学生版", price: "19", unit: "/月", desc: "最受欢迎，学生认证后专享", features: ["无限AI对话时长", "四六级/雅思/托福专项", "全部场景话题库", "详细发音&流利度报告", "AI写作批改", "学习计划定制"], cta: "认证学生身份", featured: true },
    { name: "Pro 年付", price: "15", unit: "/月", desc: "年付¥179，省¥49", features: ["Pro全部功能", "1对1真人外教月卡1张", "雅思/托福模考3次", "学习资料包"], cta: "选年付更省", featured: false },
  ];
  return (
    <section id="pricing" className="bg-orange-50/30 px-6 py-24">
      <div className="mx-auto max-w-5xl">
        <h2 className="mb-4 text-center text-4xl font-black tracking-tight text-gray-900">学生价，无压力</h2>
        <p className="mx-auto mb-16 max-w-xl text-center text-lg text-gray-500">比一杯奶茶还便宜，投资自己的口语能力</p>
        <div className="grid gap-8 lg:grid-cols-3">
          {plans.map((p) => (
            <div
              key={p.name}
              className={`relative rounded-3xl bg-white p-8 text-center shadow-xl ${
                p.featured ? "border-2 border-orange-500 ring-4 ring-orange-500/20" : "border border-gray-200"
              }`}
            >
              {p.featured && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-orange-600 px-4 py-1 text-xs font-semibold text-white">
                  最受欢迎
                </div>
              )}
              <h3 className="mb-2 text-xl font-semibold text-gray-900">{p.name}</h3>
              <div className="my-6 text-5xl font-extrabold text-gray-900">
                ¥{p.price}
                <span className="text-base font-normal text-gray-500">{p.unit}</span>
              </div>
              <p className="mb-6 text-gray-500">{p.desc}</p>
              <ul className="mb-8 space-y-1 text-left text-gray-600">
                {p.features.map((feat) => (
                  <li key={feat} className="flex items-center gap-2 py-2">
                    <span className="font-bold text-orange-500">&#10003;</span> {feat}
                  </li>
                ))}
              </ul>
              <a
                href="#cta"
                className={`block w-full rounded-lg py-3 text-center font-semibold transition-colors ${
                  p.featured
                    ? "bg-orange-500 text-white hover:bg-orange-600"
                    : "border-2 border-orange-500 text-orange-600 hover:bg-orange-50"
                }`}
              >
                {p.cta}
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FAQ() {
  return (
    <section id="faq" className="bg-white px-6 py-24">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchemaStudent) }}
      />
      <div className="mx-auto max-w-3xl">
        <h2 className="mb-12 text-center text-4xl font-black tracking-tight text-gray-900">常见问题</h2>
        <div className="space-y-4">
          {faqStudent.map((item) => (
            <details key={item.q} className="group rounded-2xl border border-gray-200 bg-white p-6 open:shadow-md">
              <summary className="cursor-pointer text-lg font-semibold text-gray-900">
                {item.q}
                <span className="float-right text-gray-400 transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-4 text-gray-600">{item.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section id="cta" className="bg-orange-600 px-6 py-24 text-center text-white">
      <div className="mx-auto max-w-3xl">
        <h2 className="mb-4 text-4xl font-black tracking-tight">今天就开口说第一句</h2>
        <p className="mb-10 text-xl opacity-90">7天免费Pro体验，不用绑卡，不好用卸载就行。</p>
        <a
          href="#"
          className="inline-block rounded-lg bg-white px-8 py-3 text-lg font-semibold text-orange-600 transition-colors hover:bg-gray-100"
        >
          免费开始练口语
        </a>
        <p className="mt-6 text-sm opacity-75">已有 50,000+ 大学生在用 · App Store 4.8分</p>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-gray-200 bg-white px-6 py-10 text-center text-gray-500">
      <p>&copy; 2026 FluentUp. 让每个大学生都敢说英语。</p>
    </footer>
  );
}

export default function StudentLandingPage() {
  return (
    <main>
      <Navbar />
      <Hero />
      <Features />
      <Testimonials />
      <Pricing />
      <FAQ />
      <CTASection />
      <Footer />
    </main>
  );
}
